-- ============================================================================
--  农业交易系统 · 权限与多租户 数据库结构（修订版 v2）
--  数据库：PostgreSQL 16+
--
--  设计要点：
--    1. sys schema = 系统级（用户/租户/权限/数据范围），全局共享
--       biz schema = 租户级业务数据，所有表强制 tenant_id
--    2. 共享库共享表 + tenant_id 列隔离，应用层拦截器强制注入
--    3. 额外启用 PG RLS 作为第二道保险（防应用层被绕过）
--    4. 租户/身份/应用/数据范围策略全部表驱动，新增类型零 DDL 改动
--
--  v2 相对 v1 的变更：
--    a. 所有主键改为 bigint GENERATED BY DEFAULT AS IDENTITY（v1 裸 bigint 无序列）
--    b. sys.user_account.password 统一为 password（v1 DDL 与 INSERT 列名不一致）
--    c. 移除 tg_set_updated_at 及全部 updated 触发器，updated_at 改由应用层维护
--    d. 修复 RLS 小节：函数/角色先建，再建策略（v1 会报函数不存在）
--    e. 新增 org / tenant 的 path 级联维护，避免移动节点后子树 path 失效
--    f. data_scope_binding 增加表达式唯一索引，防止同一策略重复绑定
--    g. login_log / audit_log 增加 DEFAULT 分区，避免缺分区导致写入失败
--    h. 权限快照查询（11.2）补充租户管理员短路分支
--
--  约定：updated_at 由应用层在 INSERT / UPDATE 时显式写入，
--        数据库仅保留 DEFAULT now() 作为插入兜底，不再有任何维护触发器。
-- ============================================================================

CREATE SCHEMA IF NOT EXISTS sys;
CREATE SCHEMA IF NOT EXISTS biz;

COMMENT
ON SCHEMA sys IS '系统级：用户、租户、应用、权限、数据范围策略';
COMMENT
ON SCHEMA biz IS '租户级业务数据，所有表强制 tenant_id 隔离';
-- ============================================================================
--  零、触发器函数
--
--  v2 起不再使用数据库触发器维护 updated_at，该列完全由应用层写入。
--  仅保留组织树 / 租户树 path 的物化路径维护（涉及递归子树，交给 DB 更可靠）。
-- ============================================================================

-- 组织路径维护（插入 / 移动节点时重算 path）
CREATE
OR REPLACE FUNCTION sys.tg_rebuild_org_path() RETURNS trigger AS $$
DECLARE
v_parent_path  varchar(512);
    v_parent_level
int;
BEGIN
    IF
NEW.parent_id IS NULL THEN
        NEW.path     = '/' || NEW.id || '/';
        NEW.level_no
= 1;
ELSE
SELECT o.path, o.level_no
INTO v_parent_path, v_parent_level
FROM sys.org o
WHERE o.id = NEW.parent_id;
IF
NOT FOUND THEN
            RAISE EXCEPTION 'sys.org: parent_id=% does not exist', NEW.parent_id;
END IF;
        NEW.path
= v_parent_path || NEW.id || '/';
        NEW.level_no
= v_parent_level + 1;
END IF;
RETURN NEW;
END;
$$
LANGUAGE plpgsql;

-- 组织路径级联：移动节点后同步修正整棵子树的 path / level_no。
-- 若不级联，ORG_TREE 数据范围按 path LIKE '/3/17/%' 下钻时会静默漏掉整棵子树。
-- 本触发器不修改 parent_id，因此 WHEN 条件不满足，不会递归触发自身。
CREATE
OR REPLACE FUNCTION sys.tg_cascade_org_path() RETURNS trigger AS $$
BEGIN
UPDATE sys.org o
SET path     = NEW.path || substring(o.path from length(OLD.path) + 1),
    level_no = NEW.level_no + (o.level_no - OLD.level_no)
WHERE o.tenant_id = NEW.tenant_id
  AND o.path LIKE OLD.path || '%'
  AND o.id <> NEW.id;
RETURN NULL;
END;
$$
LANGUAGE plpgsql;

-- 租户路径维护（预留：代理商 -> 下级代理）
CREATE
OR REPLACE FUNCTION sys.tg_rebuild_tenant_path() RETURNS trigger AS $$
DECLARE
v_parent_path  varchar(512);
    v_parent_level
int;
BEGIN
    IF
NEW.parent_id IS NULL THEN
        NEW.path     = '/' || NEW.id || '/';
        NEW.level_no
= 1;
ELSE
SELECT t.path, t.level_no
INTO v_parent_path, v_parent_level
FROM sys.tenant t
WHERE t.id = NEW.parent_id;
IF
NOT FOUND THEN
            RAISE EXCEPTION 'sys.tenant: parent_id=% does not exist', NEW.parent_id;
END IF;
        NEW.path
= v_parent_path || NEW.id || '/';
        NEW.level_no
= v_parent_level + 1;
END IF;
RETURN NEW;
END;
$$
LANGUAGE plpgsql;

CREATE
OR REPLACE FUNCTION sys.tg_cascade_tenant_path() RETURNS trigger AS $$
BEGIN
UPDATE sys.tenant t
SET path     = NEW.path || substring(t.path from length(OLD.path) + 1),
    level_no = NEW.level_no + (t.level_no - OLD.level_no)
WHERE t.path LIKE OLD.path || '%'
  AND t.id <> NEW.id;
RETURN NULL;
END;
$$
LANGUAGE plpgsql;

-- ============================================================================
--  一、系统级基础数据
-- ============================================================================

-- ---------- 1.1 租户类型（村 / 农贸市场 / 化肥农药厂或代理商）----------
CREATE TABLE sys.tenant_type
(
    id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code         varchar(64)  NOT NULL,
    name         varchar(128) NOT NULL,
    description  text,
    -- 组织层级模板，驱动租户初始化时自动建组织树
    -- 例：[{"code":"VILLAGE","name":"村"},{"code":"GROUP","name":"村民小组"}]
    org_levels   jsonb        NOT NULL DEFAULT '[]'::jsonb,
    -- 默认启用的应用 code 列表，创建租户时自动开通
    -- 注意：与 sys.tenant_type_app 存在语义重叠，二者需保持一致；
    --       tenant_type_app 是权威来源，本列仅作创建租户时的快捷默认值。
    default_apps jsonb        NOT NULL DEFAULT '[]'::jsonb,
    status       smallint     NOT NULL DEFAULT 1,     -- 1启用 0停用
    builtin      boolean      NOT NULL DEFAULT false, -- 内置类型不可删除
    sort_no      int          NOT NULL DEFAULT 0,
    created_at   timestamptz  NOT NULL DEFAULT now(),
    updated_at   timestamptz  NOT NULL DEFAULT now(), -- 应用层维护
    deleted_at   timestamptz,
    created_by   bigint,
    updated_by   bigint,
    deleted   bool       NOT NULL DEFAULT false,
    deleted_by   bigint,
    CONSTRAINT uk_tenant_type_code UNIQUE (code)

);
CREATE INDEX idx_tenant_type_status ON sys.tenant_type (status) WHERE deleted_at IS NULL;
COMMENT
ON TABLE  sys.tenant_type            IS '租户类型：表驱动，新增类型无需改代码';
COMMENT
ON COLUMN sys.tenant_type.org_levels IS '组织层级模板，创建租户时据此生成默认组织树';
COMMENT
ON COLUMN sys.tenant_type.updated_at IS '由应用层写入，数据库不再自动维护';


-- ---------- 1.2 应用（权限的集合体）----------
CREATE TABLE sys.app
(
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code        varchar(64)  NOT NULL,
    name        varchar(128) NOT NULL,
    type        varchar(24)  NOT NULL DEFAULT 'BUSINESS', -- BUSINESS业务 ADMIN管理 PORTAL门户
    entry_url   varchar(255),                             -- 前端入口
    icon        varchar(128),
    description text,
    status      smallint     NOT NULL DEFAULT 1,
    builtin     boolean      NOT NULL DEFAULT false,
    sort_no     int          NOT NULL DEFAULT 0,
    created_at  timestamptz  NOT NULL DEFAULT now(),
    updated_at  timestamptz  NOT NULL DEFAULT now(),      -- 应用层维护
    deleted_at  timestamptz,
    created_by   bigint,
    updated_by   bigint,
    deleted   bool       NOT NULL DEFAULT false,
    deleted_by   bigint,
    CONSTRAINT uk_app_code UNIQUE (code),
    CONSTRAINT ck_app_type CHECK (type IN ('BUSINESS', 'ADMIN', 'PORTAL'))

);
COMMENT
ON TABLE sys.app IS '应用：功能权限的聚合单元，一个应用 = 一整套权限';


-- ---------- 1.3 租户类型 <-> 应用（决定哪类租户能看到哪些应用）----------
CREATE TABLE sys.tenant_type_app
(
    id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_type_id bigint      NOT NULL REFERENCES sys.tenant_type (id),
    app_id         bigint      NOT NULL REFERENCES sys.app (id),
    is_default_app boolean     NOT NULL DEFAULT false, -- 登录后默认进入
    is_required    boolean     NOT NULL DEFAULT false, -- 是否强制开通不可关闭
    sort_no        int         NOT NULL DEFAULT 0,
    created_at     timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT uk_tenant_type_app UNIQUE (tenant_type_id, app_id)
);
CREATE INDEX idx_tta_app ON sys.tenant_type_app (app_id);
COMMENT
ON TABLE sys.tenant_type_app IS '租户类型的应用可见范围：农户可见多个应用，商贩仅可见商贩交易';

-- ---------- 1.4 功能权限（系统级，随应用打包发布）----------
CREATE TABLE sys.permission
(
    id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    app_id         bigint       NOT NULL REFERENCES sys.app (id),
    parent_id      bigint REFERENCES sys.permission (id),
    code           varchar(128) NOT NULL,               -- 如 trade:order:create
    name           varchar(128) NOT NULL,
    type           varchar(24)  NOT NULL DEFAULT 'API', -- MENU菜单 BUTTON按钮 API接口 ELEMENT界面元素
    api_method     varchar(16),                         -- GET/POST/PUT/DELETE/*
    api_pattern    varchar(512),                        -- Ant 通配：/api/trade/orders/**
    component_path varchar(255),                        -- 前端组件路径（MENU 用）
    icon           varchar(128),
    sort_no        int          NOT NULL DEFAULT 0,
    status         smallint     NOT NULL DEFAULT 1,
    builtin        boolean      NOT NULL DEFAULT true,  -- 系统内置，租户不可增删改
    remark         text,
    created_at     timestamptz  NOT NULL DEFAULT now(),
    updated_at     timestamptz  NOT NULL DEFAULT now(), -- 应用层维护
    deleted_at     timestamptz,
    created_by   bigint,
    updated_by   bigint,
    deleted   bool       NOT NULL DEFAULT false,
    deleted_by   bigint,
    CONSTRAINT uk_permission_app_code UNIQUE (app_id, code),
    CONSTRAINT ck_permission_type CHECK (type IN ('MENU', 'BUTTON', 'API', 'ELEMENT'))

);
CREATE INDEX idx_permission_app ON sys.permission (app_id) WHERE deleted_at IS NULL;
CREATE INDEX idx_permission_parent ON sys.permission (parent_id) WHERE deleted_at IS NULL;
CREATE INDEX idx_permission_api ON sys.permission (api_method, api_pattern) WHERE deleted_at IS NULL AND api_pattern IS NOT NULL;
COMMENT
ON TABLE sys.permission IS '功能权限：系统级数据，由应用启动时从 permission.yml 同步，租户只读';


-- ---------- 1.5 身份类型（农户 / 商贩 / 化肥农药商贩）----------
CREATE TABLE sys.identity_type
(
    id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code           varchar(64)  NOT NULL,
    name           varchar(128) NOT NULL,
    tenant_type_id bigint REFERENCES sys.tenant_type (id), -- NULL = 通用身份
    description    text,
    builtin        boolean      NOT NULL DEFAULT false,
    sort_no        int          NOT NULL DEFAULT 0,
    created_at     timestamptz  NOT NULL DEFAULT now(),
    updated_at     timestamptz  NOT NULL DEFAULT now(),    -- 应用层维护
    deleted_at     timestamptz,
    created_by   bigint,
    updated_by   bigint,
    deleted   bool       NOT NULL DEFAULT false,
    deleted_by   bigint,
    CONSTRAINT uk_identity_type_code UNIQUE (code)

);
COMMENT
ON TABLE sys.identity_type IS '身份类型：表驱动，支持后续新增用户类型';


-- ============================================================================
--  二、租户与组织
-- ============================================================================

-- ---------- 2.1 租户 ----------
CREATE TABLE sys.tenant
(
    id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_type_id bigint       NOT NULL REFERENCES sys.tenant_type (id),
    parent_id      bigint REFERENCES sys.tenant (id),         -- 预留：代理商 -> 下级代理
    path           varchar(512) NOT NULL DEFAULT '/',         -- 租户树路径 /1/12/135/
    level_no       int          NOT NULL DEFAULT 1,
    code           varchar(64)  NOT NULL,                     -- 租户唯一编码
    name           varchar(128) NOT NULL,
    short_name     varchar(64),
    region_code    varchar(12),                               -- 行政区划码，便于按地区运营
    region_name    varchar(128),
    address        varchar(255),
    contact_name   varchar(64),
    contact_phone  varchar(32),
    status         smallint     NOT NULL DEFAULT 1,           -- 1正常 0待审核 2冻结 3注销
    expire_at      timestamptz,
    config         jsonb        NOT NULL DEFAULT '{}'::jsonb, -- 租户个性化配置（菜单、参数、开关）
    created_by     bigint,
    created_at     timestamptz  NOT NULL DEFAULT now(),
    updated_at     timestamptz  NOT NULL DEFAULT now(),       -- 应用层维护
    deleted_at     timestamptz,
    updated_by   bigint,
    deleted   bool       NOT NULL DEFAULT false,
    deleted_by   bigint,
    CONSTRAINT uk_tenant_code UNIQUE (code),
    CONSTRAINT ck_tenant_status CHECK (status IN (0, 1, 2, 3))

);
CREATE INDEX idx_tenant_type ON sys.tenant (tenant_type_id) WHERE deleted_at IS NULL;
CREATE INDEX idx_tenant_parent ON sys.tenant (parent_id) WHERE deleted_at IS NULL;
CREATE INDEX idx_tenant_path ON sys.tenant (path text_pattern_ops);
CREATE INDEX idx_tenant_region ON sys.tenant (region_code) WHERE deleted_at IS NULL;
CREATE INDEX idx_tenant_status ON sys.tenant (status) WHERE deleted_at IS NULL;
COMMENT
ON TABLE sys.tenant IS '租户：村 / 农贸市场 / 化肥农药厂或代理商，数据隔离的基本单位';

-- v2 新增：v1 中 path 仅有 DEFAULT '/'，无任何维护逻辑，树形下钻不可用
CREATE TRIGGER trg_tenant_path
    BEFORE INSERT OR
UPDATE OF parent_id
ON sys.tenant
    FOR EACH ROW EXECUTE FUNCTION sys.tg_rebuild_tenant_path();
CREATE TRIGGER trg_tenant_path_cascade
    AFTER UPDATE OF parent_id
    ON sys.tenant
    FOR EACH ROW WHEN (OLD.parent_id IS DISTINCT FROM NEW.parent_id)
    EXECUTE FUNCTION sys.tg_cascade_tenant_path();

-- ---------- 2.2 组织（租户内部组织树，数据权限下钻用）----------
CREATE TABLE sys.org
(
    id               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id        bigint       NOT NULL REFERENCES sys.tenant (id) ON DELETE CASCADE,
    parent_id        bigint REFERENCES sys.org (id),
    path             varchar(512) NOT NULL,               -- /3/17/42/，由触发器维护
    level_no         int          NOT NULL DEFAULT 1,     -- 由触发器维护
    code             varchar(64),
    name             varchar(128) NOT NULL,               -- 村民小组 / 摊位区 / 门店
    leader_member_id bigint,                              -- 组织负责人（用于 MEMBER_TEAM 范围）
    sort_no          int          NOT NULL DEFAULT 0,
    status           smallint     NOT NULL DEFAULT 1,
    created_at       timestamptz  NOT NULL DEFAULT now(),
    updated_at       timestamptz  NOT NULL DEFAULT now(), -- 应用层维护
    deleted_at       timestamptz,
    created_by   bigint,
    updated_by   bigint,
    deleted   bool       NOT NULL DEFAULT false,
    deleted_by   bigint,
    CONSTRAINT uk_org_tenant_code UNIQUE (tenant_id, code)

);
CREATE INDEX idx_org_tenant ON sys.org (tenant_id) WHERE deleted_at IS NULL;
CREATE INDEX idx_org_path ON sys.org (path text_pattern_ops);
CREATE INDEX idx_org_parent ON sys.org (parent_id) WHERE deleted_at IS NULL;
COMMENT
ON TABLE sys.org IS '租户内组织树：支撑 ORG_SELF / ORG_TREE 类数据范围';

CREATE TRIGGER trg_org_path
    BEFORE INSERT OR
UPDATE OF parent_id
ON sys.org
    FOR EACH ROW EXECUTE FUNCTION sys.tg_rebuild_org_path();
CREATE TABLE "sys"."user_account"
(
    id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username      varchar(64),
    phone         varchar(20),
    email         varchar(128),
    password varchar(128),                        -- Argon2id / bcrypt
    real_name     varchar(64),
    id_card_no    bytea,                               -- 加密存储（pgcrypto 或应用层加密）
    avatar        varchar(255),
    gender        smallint,
    user_kind     varchar(24)  NOT NULL DEFAULT 'NORMAL',  -- NORMAL 普通 / SUPER_ADMIN 超管 / SYSTEM 系统账号
    status        smallint     NOT NULL DEFAULT 1,     -- 1正常 0未激活 2冻结 3注销
    "pwd_updated_at"   timestamptz,
    "pwd_expire_at"    timestamptz,
    "last_login_at"    timestamptz,
    "last_login_ip"    inet,
    "login_fail_count" smallint                                       NOT NULL DEFAULT 0,
    "locked_until"     timestamptz,
    "created_by"       bigint,
    "created_at"       timestamptz NOT NULL DEFAULT now(),
    "updated_by"       bigint,
    "updated_at"       timestamptz NOT NULL DEFAULT now(),
    "deleted"          bool                                       NOT NULL DEFAULT false,
    "deleted_by"       bigint,
    "deleted_at"       timestamptz,

    CONSTRAINT ck_user_kind CHECK (user_kind IN ('NORMAL', 'SUPER_ADMIN', 'SYSTEM'))
)
;


-- ============================================================================
--  三、用户 / 成员 / 身份
-- ============================================================================

-- ---------- 3.1 用户（自然人，登录主体）----------
-- v2 新增：移动节点时同步修正子树，否则 ORG_TREE 会静默漏数据
CREATE TRIGGER trg_org_path_cascade
    AFTER UPDATE OF parent_id
    ON sys.org
    FOR EACH ROW WHEN (OLD.parent_id IS DISTINCT FROM NEW.parent_id)
    EXECUTE FUNCTION sys.tg_cascade_org_path();
-- 注意：PostgreSQL 的 UNIQUE 约束不支持 WHERE 子句，部分唯一只能用 CREATE UNIQUE INDEX。
-- 语义：已注销（deleted_at 非空）的用户不占用手机号/用户名，允许重新注册复用。
CREATE UNIQUE INDEX uk_user_phone ON sys.user_account (phone) WHERE phone IS NOT NULL AND deleted_at IS NULL;
CREATE UNIQUE INDEX uk_user_username ON sys.user_account (username) WHERE username IS NOT NULL AND deleted_at IS NULL;
CREATE INDEX idx_user_kind ON sys.user_account (user_kind) WHERE deleted_at IS NULL;
COMMENT
ON TABLE  sys.user_account           IS '用户：自然人，全局唯一，登录主体';
COMMENT
ON COLUMN sys.user_account.user_kind IS 'SUPER_ADMIN 为特殊用户：不属任何租户，拥有全部权限';

-- ---------- 3.2 成员（用户 @ 租户 = 权限的实际授予对象）----------
CREATE TABLE sys.member
(
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id       bigint      NOT NULL REFERENCES sys.tenant (id) ON DELETE CASCADE,
    user_id         bigint      NOT NULL REFERENCES sys.user_account (id),
    member_no       varchar(64),                             -- 租户内成员编号
    display_name    varchar(64),                             -- 在租户内展示的名称（可与真实姓名不同）
    org_id          bigint REFERENCES sys.org (id),          -- 主组织（村民小组 / 摊位区）
    is_tenant_admin boolean     NOT NULL DEFAULT false,      -- 租户管理员：拥有全部应用权限
    status          smallint    NOT NULL DEFAULT 1,          -- 1正常 0待审核 2停用 3退出
    joined_at       timestamptz NOT NULL DEFAULT now(),
    profile         jsonb       NOT NULL DEFAULT '{}'::jsonb,-- 扩展信息（摊位号、经营品类、资质等）
    invited_by      bigint,
    created_at      timestamptz NOT NULL DEFAULT now(),
    updated_at      timestamptz NOT NULL DEFAULT now(),      -- 应用层维护
    deleted_at      timestamptz,
    created_by   bigint,
    updated_by   bigint,
    deleted   bool       NOT NULL DEFAULT false,
    deleted_by   bigint,
    CONSTRAINT uk_member_tenant_user UNIQUE (tenant_id, user_id),
    CONSTRAINT ck_member_status CHECK (status IN (0, 1, 2, 3))

);
CREATE INDEX idx_member_user ON sys.member (user_id) WHERE deleted_at IS NULL;
CREATE INDEX idx_member_tenant ON sys.member (tenant_id, status) WHERE deleted_at IS NULL;
CREATE INDEX idx_member_org ON sys.member (org_id) WHERE deleted_at IS NULL;
CREATE INDEX idx_member_admin ON sys.member (tenant_id) WHERE is_tenant_admin AND deleted_at IS NULL;
COMMENT
ON TABLE sys.member IS '成员：用户在某租户内的身份，权限授予的最小载体。切租户 = 切 member';


-- ---------- 3.3 成员身份（一个成员可同时是农户/商贩等多重身份）----------
CREATE TABLE sys.member_identity
(
    id               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id        bigint      NOT NULL REFERENCES sys.member (id) ON DELETE CASCADE,
    identity_type_id bigint      NOT NULL REFERENCES sys.identity_type (id),
    is_primary       boolean     NOT NULL DEFAULT false,       -- 主身份
    status           smallint    NOT NULL DEFAULT 1,
    verified_at      timestamptz,                              -- 实名/资质认证时间
    verified_by      bigint,
    credential       jsonb       NOT NULL DEFAULT '{}'::jsonb, -- 资质材料（营业执照、摊位证等）
    created_at       timestamptz NOT NULL DEFAULT now(),
    updated_at       timestamptz NOT NULL DEFAULT now(),       -- 应用层维护
    deleted_at       timestamptz,
    created_by   bigint,
    updated_by   bigint,
    deleted   bool       NOT NULL DEFAULT false,
    deleted_by   bigint,
    CONSTRAINT uk_member_identity UNIQUE (member_id, identity_type_id)

);
CREATE INDEX idx_mi_type ON sys.member_identity (identity_type_id) WHERE deleted_at IS NULL;
COMMENT
ON TABLE sys.member_identity IS '成员身份：支持同一租户内多重身份，如既卖菜又买菜';


-- ---------- 3.4 成员 <-> 组织（可跨组织兼任）----------
CREATE TABLE sys.member_org
(
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id  bigint      NOT NULL REFERENCES sys.member (id) ON DELETE CASCADE,
    org_id     bigint      NOT NULL REFERENCES sys.org (id) ON DELETE CASCADE,
    is_primary boolean     NOT NULL DEFAULT false,
    created_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT uk_member_org UNIQUE (member_id, org_id)
);
CREATE INDEX idx_mo_org ON sys.member_org (org_id);
COMMENT
ON TABLE sys.member_org IS '成员与组织的多对多关系，支撑按组织下钻的数据范围';


-- ============================================================================
--  四、角色与授权（租户自定义）
-- ============================================================================

-- ---------- 4.1 角色（租户内、按应用划分，支持继承 = RBAC1）----------
CREATE TABLE sys.role
(
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id       bigint       NOT NULL REFERENCES sys.tenant (id) ON DELETE CASCADE,
    app_id          bigint       NOT NULL REFERENCES sys.app (id),
    parent_id       bigint REFERENCES sys.role (id),     -- 角色继承
    code            varchar(64)  NOT NULL,
    name            varchar(128) NOT NULL,
    description     text,
    is_tenant_admin boolean      NOT NULL DEFAULT false, -- 租户管理员角色：权限自动跟随应用
    builtin         boolean      NOT NULL DEFAULT false, -- 系统预置，不可删除
    status          smallint     NOT NULL DEFAULT 1,
    sort_no         int          NOT NULL DEFAULT 0,
    created_by      bigint,
    created_at      timestamptz  NOT NULL DEFAULT now(),
    updated_at      timestamptz  NOT NULL DEFAULT now(), -- 应用层维护
    deleted_at      timestamptz,
    updated_by   bigint,
    deleted   bool       NOT NULL DEFAULT false,
    deleted_by   bigint,
    CONSTRAINT uk_role_tenant_app_code UNIQUE (tenant_id, app_id, code)

);
CREATE INDEX idx_role_tenant_app ON sys.role (tenant_id, app_id) WHERE deleted_at IS NULL;
CREATE INDEX idx_role_parent ON sys.role (parent_id) WHERE deleted_at IS NULL;
COMMENT
ON TABLE sys.role IS '租户自定义角色，按应用划分；parent_id 支持角色继承（RBAC1）';

-- ---------- 4.2 角色 <-> 功能权限 ----------
CREATE TABLE sys.role_permission
(
    id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_id       bigint      NOT NULL REFERENCES sys.role (id) ON DELETE CASCADE,
    permission_id bigint      NOT NULL REFERENCES sys.permission (id) ON DELETE CASCADE,
    created_at    timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT uk_role_permission UNIQUE (role_id, permission_id)
);
CREATE INDEX idx_rp_permission ON sys.role_permission (permission_id);
COMMENT
ON TABLE sys.role_permission IS '角色包含的功能权限（仅限该角色所属应用下的权限）';


-- ---------- 4.3 成员 <-> 角色 ----------
CREATE TABLE sys.member_role
(
    id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id      bigint      NOT NULL REFERENCES sys.member (id) ON DELETE CASCADE,
    role_id        bigint      NOT NULL REFERENCES sys.role (id) ON DELETE CASCADE,
    effective_from timestamptz NOT NULL DEFAULT now(),
    effective_to   timestamptz, -- NULL = 长期有效
    granted_by     bigint,
    created_at     timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT uk_member_role UNIQUE (member_id, role_id),
    CONSTRAINT ck_mr_effective CHECK (effective_to IS NULL OR effective_to > effective_from)
);
CREATE INDEX idx_mr_role ON sys.member_role (role_id);
CREATE INDEX idx_mr_effective ON sys.member_role (member_id, effective_from, effective_to);
COMMENT
ON TABLE sys.member_role IS '成员被授予的角色；权限快照计算时展开角色继承树';


-- ============================================================================
--  五、全局角色（超级管理员专用，跨租户）
-- ============================================================================

CREATE TABLE sys.global_role
(
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code        varchar(64)  NOT NULL,
    name        varchar(128) NOT NULL,
    description text,
    is_super    boolean      NOT NULL DEFAULT false, -- 超管角色：绕过全部校验
    builtin     boolean      NOT NULL DEFAULT false,
    status      smallint     NOT NULL DEFAULT 1,
    created_at  timestamptz  NOT NULL DEFAULT now(),
    updated_at  timestamptz  NOT NULL DEFAULT now(), -- 应用层维护
    created_by   bigint,
    updated_by   bigint,
    deleted   bool       NOT NULL DEFAULT false,
    deleted_by   bigint,
    deleted_at   timestamptz,
    CONSTRAINT uk_global_role_code UNIQUE (code)

);
COMMENT
ON TABLE sys.global_role IS '全局角色：不属于任何租户，用于超级管理员及未来的运营角色';

CREATE TABLE sys.global_role_permission
(
    id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    global_role_id bigint      NOT NULL REFERENCES sys.global_role (id) ON DELETE CASCADE,
    permission_id  bigint      NOT NULL REFERENCES sys.permission (id) ON DELETE CASCADE,
    created_at     timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT uk_grp UNIQUE (global_role_id, permission_id)
);

CREATE TABLE sys.user_global_role
(
    id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id        bigint      NOT NULL REFERENCES sys.user_account (id) ON DELETE CASCADE,
    global_role_id bigint      NOT NULL REFERENCES sys.global_role (id) ON DELETE CASCADE,
    granted_by     bigint,
    created_at     timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT uk_ugr UNIQUE (user_id, global_role_id)
);
COMMENT
ON TABLE sys.user_global_role IS '用户持有的全局角色；超管用户绑定 is_super 的全局角色';


-- ============================================================================
--  六、数据权限（系统级配置，超级管理员管理）
-- ============================================================================

-- ---------- 6.1 受保护资源对象 ----------
CREATE TABLE sys.data_object
(
    id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code                varchar(64)  NOT NULL,               -- 如 TRADE_ORDER
    name                varchar(128) NOT NULL,
    schema_name         varchar(64)  NOT NULL DEFAULT 'biz',
    table_name          varchar(64)  NOT NULL,               -- 如 trade_order
    tenant_column       varchar(64)  NOT NULL DEFAULT 'tenant_id',
    org_column          varchar(64),                         -- 如 org_id
    owner_member_column varchar(64),                         -- 如 created_member_id
    owner_user_column   varchar(64),                         -- 如 created_by
    default_scope_type  varchar(32)  NOT NULL DEFAULT 'TENANT_ALL',
    status              smallint     NOT NULL DEFAULT 1,
    remark              text,
    created_at          timestamptz  NOT NULL DEFAULT now(),
    updated_at          timestamptz  NOT NULL DEFAULT now(), -- 应用层维护
    created_by   bigint,
    updated_by   bigint,
    deleted   bool       NOT NULL DEFAULT false,
    deleted_by   bigint,
    deleted_at   timestamptz,
    CONSTRAINT uk_data_object_code UNIQUE (code),
    CONSTRAINT ck_do_default_scope CHECK (default_scope_type IN
                                          ('GLOBAL', 'TENANT_ALL', 'ORG_TREE', 'ORG_SELF', 'MEMBER_TEAM', 'MEMBER_SELF',
                                           'CUSTOM_SQL', 'DENY_ALL'))

);
COMMENT
ON TABLE sys.data_object IS '受数据权限保护的资源（业务表）注册表；拦截器据此改写 SQL';

-- ---------- 6.2 数据范围策略（系统预置，租户不可新建）----------
CREATE TABLE sys.data_scope_policy
(
    id               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    object_id        bigint       NOT NULL REFERENCES sys.data_object (id) ON DELETE CASCADE,
    code             varchar(64)  NOT NULL,
    name             varchar(128) NOT NULL,
    scope_type       varchar(32)  NOT NULL,
    -- CUSTOM_SQL 时的表达式，其余类型留空
    -- 例：{"where": "alias.region_code = :regionCode", "params": {"regionCode": "370700"}}
    scope_expression jsonb        NOT NULL DEFAULT '{}'::jsonb,
    effect           varchar(16)  NOT NULL DEFAULT 'ALLOW', -- ALLOW 放行 / DENY 拒绝（优先级最高）
    priority         int          NOT NULL DEFAULT 0,
    builtin          boolean      NOT NULL DEFAULT true,
    status           smallint     NOT NULL DEFAULT 1,
    description      text,
    created_at       timestamptz  NOT NULL DEFAULT now(),
    updated_at       timestamptz  NOT NULL DEFAULT now(),   -- 应用层维护
    created_by   bigint,
    updated_by   bigint,
    deleted   bool       NOT NULL DEFAULT false,
    deleted_by   bigint,
    deleted_at   timestamptz,
    CONSTRAINT uk_dsp_code UNIQUE (code),
    CONSTRAINT ck_dsp_scope CHECK (scope_type IN
                                   ('GLOBAL', 'TENANT_ALL', 'ORG_TREE', 'ORG_SELF', 'MEMBER_TEAM', 'MEMBER_SELF',
                                    'CUSTOM_SQL', 'DENY_ALL')),
    CONSTRAINT ck_dsp_effect CHECK (effect IN ('ALLOW', 'DENY'))

);
CREATE INDEX idx_dsp_object ON sys.data_scope_policy (object_id, status);
COMMENT
ON TABLE sys.data_scope_policy IS '数据范围策略：系统级预置，租户只能在其中选用，不能自建新规则';


-- ---------- 6.3 策略绑定（超级管理员的分配动作）----------
CREATE TABLE sys.data_scope_binding
(
    id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    policy_id      bigint      NOT NULL REFERENCES sys.data_scope_policy (id) ON DELETE CASCADE,
    subject_type   varchar(24) NOT NULL,               -- GLOBAL_ROLE / ROLE / MEMBER / PERMISSION
    subject_id     bigint      NOT NULL,
    app_id         bigint REFERENCES sys.app (id),     -- NULL = 不限应用
    tenant_id      bigint REFERENCES sys.tenant (id),  -- NULL = 系统级（超管分配）；有值 = 租户级收窄
    -- 租户级绑定允许收窄的最大范围，防止租户管理员自我放大
    max_scope_type varchar(32),
    priority       int         NOT NULL DEFAULT 0,
    status         smallint    NOT NULL DEFAULT 1,
    created_by     bigint,
    created_at     timestamptz NOT NULL DEFAULT now(),
    updated_at     timestamptz NOT NULL DEFAULT now(), -- 应用层维护
    updated_by   bigint,
    deleted   bool       NOT NULL DEFAULT false,
    deleted_by   bigint,
    deleted_at   timestamptz,
    CONSTRAINT ck_dsb_subject CHECK (subject_type IN ('GLOBAL_ROLE', 'ROLE', 'MEMBER', 'PERMISSION')),
    CONSTRAINT ck_dsb_max_scope CHECK (max_scope_type IS NULL OR max_scope_type IN
                                                                 ('GLOBAL', 'TENANT_ALL', 'ORG_TREE', 'ORG_SELF',
                                                                  'MEMBER_TEAM', 'MEMBER_SELF', 'CUSTOM_SQL',
                                                                  'DENY_ALL'))

);
CREATE INDEX idx_dsb_subject ON sys.data_scope_binding (subject_type, subject_id, status);
CREATE INDEX idx_dsb_tenant ON sys.data_scope_binding (tenant_id) WHERE tenant_id IS NOT NULL;
CREATE INDEX idx_dsb_app ON sys.data_scope_binding (app_id);
-- v2 新增：普通 UNIQUE 约束中 NULL 互不相等，app_id / tenant_id 为 NULL 时仍可重复绑定，
--          故用 COALESCE 表达式唯一索引兜底。
CREATE UNIQUE INDEX uk_dsb_subject_scope ON sys.data_scope_binding
    (policy_id, subject_type, subject_id, COALESCE(app_id, 0), COALESCE(tenant_id, 0));
COMMENT
ON TABLE sys.data_scope_binding IS '策略绑定：超管把系统策略挂到全局角色/角色/成员/权限点上';
COMMENT
ON COLUMN sys.data_scope_binding.max_scope_type IS '租户级绑定可收窄的上限，防止越权放大';


-- ============================================================================
--  七、上下文与审计
-- ============================================================================

-- ---------- 7.1 用户当前上下文（刷新页面/换设备可恢复）----------
CREATE TABLE sys.user_context
(
    user_id           bigint PRIMARY KEY REFERENCES sys.user_account (id) ON DELETE CASCADE,
    current_member_id bigint,
    current_tenant_id bigint,
    current_app_id    bigint,
    updated_at        timestamptz NOT NULL DEFAULT now(), -- 应用层维护,
    created_by   bigint,
    created_at   timestamptz  NOT NULL DEFAULT now(),
    updated_by   bigint,
    deleted   bool       NOT NULL DEFAULT false,
    deleted_by   bigint,
    deleted_at   timestamptz

);
COMMENT
ON TABLE sys.user_context IS '用户当前所在租户/应用，主副本在 Redis，此表用于持久化恢复';


-- ---------- 7.2 登录日志 ----------
CREATE TABLE sys.login_log
(
    id          bigint GENERATED BY DEFAULT AS IDENTITY,
    user_id     bigint,
    phone       varchar(20),
    login_type  varchar(24),          -- PASSWORD / SMS / WECHAT
    result      smallint    NOT NULL, -- 1成功 0失败
    fail_reason varchar(128),
    ip          inet,
    user_agent  text,
    created_at  timestamptz NOT NULL DEFAULT now(),
    created_by   bigint,
    updated_by   bigint,
    updated_at   timestamptz  NOT NULL DEFAULT now(),
    deleted   bool       NOT NULL DEFAULT false,
    deleted_by   bigint,
    deleted_at   timestamptz,
    PRIMARY KEY (id, created_at)

) PARTITION BY RANGE (created_at);

-- 按月分区；生产环境用定时任务（如 pg_partman）提前创建后续分区
CREATE TABLE sys.login_log_2026_09 PARTITION OF sys.login_log
    FOR VALUES FROM
(
    '2026-09-01'
) TO
(
    '2026-10-01'
);
CREATE TABLE sys.login_log_2026_10 PARTITION OF sys.login_log
    FOR VALUES FROM
(
    '2026-10-01'
) TO
(
    '2026-11-01'
);
-- v2 新增：兜底分区，避免定时任务漏建时登录日志写入直接失败
CREATE TABLE sys.login_log_default PARTITION OF sys.login_log DEFAULT;

CREATE INDEX idx_login_log_user ON sys.login_log (user_id, created_at DESC);

COMMENT
ON TABLE  sys.login_log        IS '登录日志：按月 RANGE 分区，保留 1 年';
COMMENT
ON COLUMN sys.login_log.result IS '1成功 0失败';

-- ---------- 7.3 审计日志（权限变更全量留痕）----------
CREATE TABLE sys.audit_log
(
    id                 bigint GENERATED BY DEFAULT AS IDENTITY,
    operator_user_id   bigint,
    operator_member_id bigint,
    tenant_id          bigint,
    app_id             bigint,
    module             varchar(64) NOT NULL, -- ROLE / PERMISSION / DATASCOPE / MEMBER / TENANT
    action             varchar(64) NOT NULL, -- GRANT_ROLE / REVOKE_ROLE / BIND_SCOPE / SWITCH_TENANT ...
    target_type        varchar(64),
    target_id          bigint,
    before_value       jsonb,
    after_value        jsonb,
    ip                 inet,
    remark             text,
    created_at         timestamptz NOT NULL DEFAULT now(),
    created_by   bigint,
    updated_by   bigint,
    updated_at   timestamptz  NOT NULL DEFAULT now(),
    deleted   bool       NOT NULL DEFAULT false,
    deleted_by   bigint,
    deleted_at   timestamptz,
    PRIMARY KEY (id, created_at)

) PARTITION BY RANGE (created_at);

CREATE TABLE sys.audit_log_2026_09 PARTITION OF sys.audit_log
    FOR VALUES FROM
(
    '2026-09-01'
) TO
(
    '2026-10-01'
);
CREATE TABLE sys.audit_log_2026_10 PARTITION OF sys.audit_log
    FOR VALUES FROM
(
    '2026-10-01'
) TO
(
    '2026-11-01'
);
CREATE TABLE sys.audit_log_default PARTITION OF sys.audit_log DEFAULT;

CREATE INDEX idx_audit_operator ON sys.audit_log (operator_user_id, created_at DESC);
CREATE INDEX idx_audit_tenant ON sys.audit_log (tenant_id, created_at DESC);
CREATE INDEX idx_audit_target ON sys.audit_log (target_type, target_id);
COMMENT
ON TABLE sys.audit_log IS '权限相关操作全量审计，按月分区，保留 3 年';

-- 注意：存在 DEFAULT 分区后，新增月分区需先 DETACH 并迁移其中落在该区间的行，
--      否则会因 DEFAULT 分区已包含该范围数据而创建失败。


-- ============================================================================
--  八、业务表示例（biz schema，所有表强制 tenant_id）
-- ============================================================================

-- ---------- 8.1 交易订单（商贩交易应用的核心表）----------
CREATE TABLE biz.trade_order
(
    id                    bigint GENERATED BY DEFAULT AS IDENTITY,
    tenant_id             bigint         NOT NULL,                 -- 强制隔离列
    order_no              varchar(32)    NOT NULL,
    app_id                bigint         NOT NULL,
    buyer_member_id       bigint,
    seller_member_id      bigint,
    org_id                bigint,                                  -- 数据权限 org 列
    counterpart_tenant_id bigint,                                  -- 跨租户交易对手方（村 <-> 农贸市场）
    produce_code          varchar(64),
    produce_name          varchar(128),
    quantity              numeric(18, 3) NOT NULL,
    unit                  varchar(16)    NOT NULL,
    unit_price            numeric(18, 2),
    total_amount          numeric(18, 2),                          -- 仅记录约定金额，平台不参与资金
    status                varchar(24)    NOT NULL DEFAULT 'DRAFT', -- DRAFT/CONFIRMED/CANCELLED/...
    trade_date            date           NOT NULL DEFAULT current_date,
    remark                text,
    created_by            bigint,
    created_member_id     bigint,                                  -- 数据权限 owner 列
    created_at            timestamptz    NOT NULL DEFAULT now(),
    updated_at            timestamptz    NOT NULL DEFAULT now(),   -- 应用层维护
    deleted_at            timestamptz,
    updated_by   bigint,
    deleted   bool       NOT NULL DEFAULT false,
    deleted_by   bigint,
    PRIMARY KEY (id),
    CONSTRAINT uk_order_no UNIQUE (tenant_id, order_no)

);

-- 生产分区建议（按需启用，勿一上来就分区）：
--   方案 A（推荐先不做）：单表 + (tenant_id, trade_date) 复合索引，撑到单表千万级无压力。
--   方案 B（数据量上来后）：按 trade_date 做 RANGE 分区，主键需改为 (id, trade_date)，
--                           唯一约束 uk_order_no 需改为 (tenant_id, order_no, trade_date)。
--   方案 C（大租户独立治理）：按 tenant_id 做 LIST 分区，把超大租户单独分区。
--   注意：PG 要求分区表的任何唯一约束都必须包含分区键，改造时务必同步调整主键与唯一键。

CREATE INDEX idx_order_tenant_date ON biz.trade_order (tenant_id, trade_date DESC) WHERE deleted_at IS NULL;
CREATE INDEX idx_order_tenant_org ON biz.trade_order (tenant_id, org_id) WHERE deleted_at IS NULL;
CREATE INDEX idx_order_tenant_creator ON biz.trade_order (tenant_id, created_member_id) WHERE deleted_at IS NULL;
CREATE INDEX idx_order_counterpart ON biz.trade_order (counterpart_tenant_id) WHERE deleted_at IS NULL;
COMMENT
ON TABLE  biz.trade_order IS '交易订单：只做交易确定，不落资金流水';
COMMENT
ON COLUMN biz.trade_order.counterpart_tenant_id IS '跨租户交易对手方所在租户，用于村与市场联动查询';

-- ============================================================================
--  九、PostgreSQL 行级安全（RLS）—— 第二道保险
--
--  说明：主隔离由应用层拦截器完成；RLS 用于防止 DBA 直连、脚本、BI 工具绕过应用层。
--        通过 SET LOCAL app.current_tenant = '<id>' 传入当前租户，未设置则看不到任何业务数据。
--
--  v2 修复：v1 中 CREATE POLICY 引用了在其下一段才创建的函数，而 PG 建策略时即做函数解析，
--           会抛 "function sys.current_tenant_id() does not exist"。此处改为先建依赖对象。
-- ============================================================================

-- 9.1 当前租户读取函数（未设置会话变量时返回 NULL，天然拒绝全部访问）
CREATE
OR REPLACE FUNCTION sys.current_tenant_id() RETURNS bigint AS $$
DECLARE
v_raw text := current_setting('app.current_tenant', true);
BEGIN
    IF
v_raw IS NULL OR v_raw = '' THEN
        RETURN NULL;
END IF;
RETURN v_raw::bigint;
EXCEPTION
    WHEN OTHERS THEN RETURN NULL;
END;
$$
LANGUAGE plpgsql STABLE PARALLEL SAFE;

COMMENT
ON FUNCTION sys.current_tenant_id()
    IS '从会话变量 app.current_tenant 读取当前租户，供 RLS 策略使用';

-- 9.2 旁路角色：超管 / 运维账号可绕过 RLS（仅授予极少数账号，且必须在审计下使用）
--     PG 无 CREATE ROLE IF NOT EXISTS，用 DO 块保证脚本可重复执行。
DO
$$
BEGIN
    IF
NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'agri_bypass_rls') THEN
CREATE ROLE agri_bypass_rls NOLOGIN;
END IF;
END
$$;

-- 9.3 启用 RLS 并建立策略（依赖已在 9.1 / 9.2 就绪）
ALTER TABLE biz.trade_order ENABLE ROW LEVEL SECURITY;
ALTER TABLE biz.trade_order FORCE ROW LEVEL SECURITY; -- 对表 owner 同样生效

CREATE
POLICY trade_order_tenant_isolation ON biz.trade_order
    USING      (tenant_id = sys.current_tenant_id())
    WITH CHECK (tenant_id = sys.current_tenant_id());

CREATE
POLICY trade_order_bypass ON biz.trade_order TO agri_bypass_rls
    USING (true) WITH CHECK (true);

-- 使用方式：
--   业务账号：BEGIN; SET LOCAL app.current_tenant = '1001'; ... COMMIT;
--   超管账号：GRANT agri_bypass_rls TO <ops_user>;（需该用户重新登录生效）
--   注意：跨租户统计（如超管看全平台订单）若走 RLS，会被 tenant_id = NULL 全部过滤掉，
--         必须显式持有 agri_bypass_rls 角色，或按租户逐个 SET LOCAL 后再聚合。


-- ============================================================================
--  十、初始化数据
-- ============================================================================

-- ---------- 租户类型 ----------
INSERT INTO sys.tenant_type (id, code, name, description, org_levels, default_apps, builtin, sort_no)
VALUES (1, 'VILLAGE', '村', '以村为单位的农户租户',
        '[
          {
            "code": "VILLAGE",
            "name": "村"
          },
          {
            "code": "GROUP",
            "name": "村民小组"
          }
        ]'::jsonb,
        '[
          "TRADE",
          "AGRO_INPUT"
        ]'::jsonb, true, 10),
       (2, 'MARKET', '农贸市场', '以农贸市场为单位的商贩租户',
        '[
          {
            "code": "MARKET",
            "name": "市场"
          },
          {
            "code": "ZONE",
            "name": "摊位区"
          }
        ]'::jsonb,
        '[
          "TRADE"
        ]'::jsonb, true, 20),
       (3, 'AGENT', '化肥农药厂/代理商', '以化肥农药厂或代理商为单位的农资租户',
        '[
          {
            "code": "COMPANY",
            "name": "公司"
          },
          {
            "code": "STORE",
            "name": "门店"
          }
        ]'::jsonb,
        '[
          "AGRO_INPUT"
        ]'::jsonb, true, 30);

-- ---------- 应用 ----------
INSERT INTO sys.app (id, code, name, type, entry_url, icon, description, builtin, sort_no)
VALUES (1, 'TRADE', '商贩交易', 'BUSINESS', '/trade', 'shopping-cart', '农产品供需撮合与交易确定', true, 10),
       (2, 'AGRO_INPUT', '农资交易', 'BUSINESS', '/agro-input', 'spray', '化肥/农药交易确定', true, 20),
       (3, 'ADMIN', '系统管理', 'ADMIN', '/admin', 'setting', '超级管理员后台', true, 90);

-- ---------- 租户类型 <-> 应用 ----------
INSERT INTO sys.tenant_type_app (tenant_type_id, app_id, is_default_app, is_required)
VALUES (1, 1, true, true),   -- 村(农户) 可用 商贩交易
       (1, 2, false, false), -- 村(农户) 可用 农资交易
       (2, 1, true, true),   -- 农贸市场(商贩) 仅可用 商贩交易
       (3, 2, true, true);
-- 农资厂/代理商 仅可用 农资交易

-- ---------- 身份类型 ----------
INSERT INTO sys.identity_type (id, code, name, tenant_type_id, builtin, sort_no)
VALUES (1, 'FARMER', '农户', 1, true, 10),
       (2, 'TRADER', '商贩', 2, true, 20),
       (3, 'AGRO_DEALER', '农资商贩', 3, true, 30),
       (4, 'VILLAGE_CADRE', '村干部', 1, false, 40);

-- ---------- 功能权限（示例，实际由应用启动时从 permission.yml 同步）----------
INSERT INTO sys.permission (id, app_id, parent_id, code, name, type, api_method, api_pattern, component_path, sort_no)
VALUES
    -- 商贩交易应用
    (1001, 1, NULL, 'trade:order', '交易管理', 'MENU', NULL, NULL, '/trade/order', 10),
    (1002, 1, 1001, 'trade:order:list', '订单查询', 'API', 'GET', '/api/trade/orders', NULL, 10),
    (1003, 1, 1001, 'trade:order:create', '发起交易', 'BUTTON', 'POST', '/api/trade/orders', NULL, 20),
    (1004, 1, 1001, 'trade:order:confirm', '确认交易', 'BUTTON', 'PUT', '/api/trade/orders/*/confirm', NULL, 30),
    (1005, 1, 1001, 'trade:order:export', '导出订单', 'BUTTON', 'GET', '/api/trade/orders/export', NULL, 40),
    (1006, 1, NULL, 'trade:publish', '货源发布', 'MENU', NULL, NULL, '/trade/publish', 20),
    (1007, 1, 1006, 'trade:publish:create', '发布货源', 'API', 'POST', '/api/trade/publishes', NULL, 10),
    -- 农资交易应用
    (2001, 2, NULL, 'agro:order', '农资订单', 'MENU', NULL, NULL, '/agro/order', 10),
    (2002, 2, 2001, 'agro:order:list', '农资订单查询', 'API', 'GET', '/api/agro/orders', NULL, 10),
    (2003, 2, 2001, 'agro:order:create', '发起农资订单', 'BUTTON', 'POST', '/api/agro/orders', NULL, 20);

-- ---------- 全局角色 ----------
INSERT INTO sys.global_role (id, code, name, description, is_super, builtin)
VALUES (1, 'SUPER_ADMIN', '超级管理员', '系统最高权限，管理租户/应用/数据权限策略', true, true),
       (2, 'OPS', '运营', '查看运营数据，不可变更权限配置', false, false);

-- ---------- 受保护数据对象 ----------
INSERT INTO sys.data_object (id, code, name, schema_name, table_name, tenant_column, org_column, owner_member_column,
                             owner_user_column, default_scope_type)
VALUES (1, 'TRADE_ORDER', '交易订单', 'biz', 'trade_order', 'tenant_id', 'org_id', 'created_member_id', 'created_by',
        'TENANT_ALL');

-- ---------- 数据范围策略（系统预置，租户只能选用）----------
INSERT INTO sys.data_scope_policy (id, object_id, code, name, scope_type, scope_expression, effect, priority, builtin,
                                   description)
VALUES (1, 1, 'TRADE_ORDER_GLOBAL', '全部租户数据', 'GLOBAL', '{}'::jsonb, 'ALLOW', 100, true, '超管专用，可跨租户查看'),
       (2, 1, 'TRADE_ORDER_TENANT_ALL', '本租户全部', 'TENANT_ALL', '{}'::jsonb, 'ALLOW', 50, true, '租户管理员默认'),
       (3, 1, 'TRADE_ORDER_ORG_TREE', '本组织及下级', 'ORG_TREE', '{}'::jsonb, 'ALLOW', 40, true, '按组织树下钻'),
       (4, 1, 'TRADE_ORDER_ORG_SELF', '仅本组织', 'ORG_SELF', '{}'::jsonb, 'ALLOW', 30, true, '仅当前组织'),
       (5, 1, 'TRADE_ORDER_TEAM', '本组织及团队', 'MEMBER_TEAM', '{}'::jsonb, 'ALLOW', 25, true, '组织内本人及下属'),
       (6, 1, 'TRADE_ORDER_SELF', '仅本人', 'MEMBER_SELF', '{}'::jsonb, 'ALLOW', 10, true, '仅看自己创建的'),
       (7, 1, 'TRADE_ORDER_DENY', '禁止访问', 'DENY_ALL', '{}'::jsonb, 'DENY', 999, true, '黑名单，最高优先级');

-- ---------- 超管默认数据范围：全局 ----------
INSERT INTO sys.data_scope_binding (policy_id, subject_type, subject_id, priority, status)
VALUES (1, 'GLOBAL_ROLE', 1, 100, 1);

-- ---------- 初始化超级管理员 ----------
-- 密码 'Admin@123456' 的 bcrypt 占位，生产必须使用强密码并由运维在首次登录后强制修改
INSERT INTO sys.user_account (id, username, phone, password, real_name, user_kind, status)
VALUES (1, 'superadmin', '13000000000',
        '$2a$10$N.zmdr9k7uOCQb376NoUnuTJ8iAt6Z5EHsM8lE9lBOsl7iKTVKIUi',
        '系统超级管理员', 'SUPER_ADMIN', 1);

INSERT INTO sys.user_global_role (user_id, global_role_id, granted_by)
VALUES (1, 1, 1);

-- ---------- identity 序列校准（手工指定 id 后必须对齐序列）----------
-- v2 说明：v1 中主键为裸 bigint，pg_get_serial_sequence 返回 NULL 导致 setval 报错；
--          现主键均为 IDENTITY，pg_get_serial_sequence 可正常解析。
SELECT setval(pg_get_serial_sequence('sys.tenant_type', 'id'), (SELECT max(id) FROM sys.tenant_type));
SELECT setval(pg_get_serial_sequence('sys.app', 'id'), (SELECT max(id) FROM sys.app));
SELECT setval(pg_get_serial_sequence('sys.identity_type', 'id'), (SELECT max(id) FROM sys.identity_type));
SELECT setval(pg_get_serial_sequence('sys.permission', 'id'), (SELECT max(id) FROM sys.permission));
SELECT setval(pg_get_serial_sequence('sys.global_role', 'id'), (SELECT max(id) FROM sys.global_role));
SELECT setval(pg_get_serial_sequence('sys.data_object', 'id'), (SELECT max(id) FROM sys.data_object));
SELECT setval(pg_get_serial_sequence('sys.data_scope_policy', 'id'), (SELECT max(id) FROM sys.data_scope_policy));
SELECT setval(pg_get_serial_sequence('sys.user_account', 'id'), (SELECT max(id) FROM sys.user_account));

-- ============================================================================
--  十一、常用查询（权限快照计算，供应用层直接使用）
-- ============================================================================

-- ---- 11.1 用户的可选身份卡片（登录后的租户/应用列表）----
-- SELECT m.id AS member_id, t.id AS tenant_id, t.name AS tenant_name, tt.code AS tenant_type,
--        a.id AS app_id, a.code AS app_code, a.name AS app_name
-- FROM sys.member m
-- JOIN sys.tenant t            ON t.id = m.tenant_id AND t.deleted_at IS NULL
-- JOIN sys.tenant_type tt      ON tt.id = t.tenant_type_id
-- JOIN sys.tenant_type_app tta ON tta.tenant_type_id = t.tenant_type_id
-- JOIN sys.app a               ON a.id = tta.app_id AND a.deleted_at IS NULL
-- WHERE m.user_id = :userId AND m.status = 1 AND m.deleted_at IS NULL AND t.status = 1;

-- ---- 11.2 权限快照（含角色继承展开 + 租户管理员短路）----
-- v2 修复：v1 的 CTE 选出了 is_tenant_admin 却从未使用，
--          导致"被标记为租户管理员但未分配任何角色"的成员算出的权限为空。
-- WITH RECURSIVE role_tree AS (
--     SELECT r.id, r.is_tenant_admin FROM sys.role r
--     JOIN sys.member_role mr ON mr.role_id = r.id
--     WHERE mr.member_id = :memberId
--       AND (mr.effective_to IS NULL OR mr.effective_to > now())
--       AND r.deleted_at IS NULL
--     UNION
--     SELECT r2.id, r2.is_tenant_admin FROM sys.role r2
--     JOIN role_tree rt ON r2.parent_id = rt.id
--     WHERE r2.deleted_at IS NULL
-- )
-- SELECT DISTINCT p.code
-- FROM role_tree rt
-- JOIN sys.role_permission rp ON rp.role_id = rt.id
-- JOIN sys.permission p       ON p.id = rp.permission_id
-- WHERE p.app_id = :appId AND p.status = 1 AND p.deleted_at IS NULL
-- UNION
-- -- 租户管理员（成员级或角色级）直接放开该应用下的全部权限
-- SELECT p.code
-- FROM sys.permission p
-- WHERE p.app_id = :appId AND p.status = 1 AND p.deleted_at IS NULL
--   AND EXISTS (
--        SELECT 1 FROM sys.member m
--        WHERE m.id = :memberId AND m.deleted_at IS NULL AND m.is_tenant_admin
--        UNION ALL
--        SELECT 1 FROM role_tree rt2 WHERE rt2.is_tenant_admin
--   );

-- ---- 11.3 数据范围（按主体精确度取最优的一条）----
-- SELECT dsp.scope_type, dsp.scope_expression, dsp.effect, dso.code AS object_code,
--        dso.schema_name, dso.table_name, dso.tenant_column, dso.org_column,
--        dso.owner_member_column, dso.owner_user_column
-- FROM sys.data_scope_binding dsb
-- JOIN sys.data_scope_policy  dsp ON dsp.id = dsb.policy_id AND dsp.status = 1
-- JOIN sys.data_object        dso ON dso.id = dsp.object_id AND dso.status = 1
-- WHERE dsb.status = 1
--   AND (dsb.app_id IS NULL OR dsb.app_id = :appId)
--   AND (dsb.tenant_id IS NULL OR dsb.tenant_id = :tenantId)
--   AND (  (dsb.subject_type = 'MEMBER'      AND dsb.subject_id = :memberId)
--       OR (dsb.subject_type = 'ROLE'        AND dsb.subject_id IN (:roleIds))
--       OR (dsb.subject_type = 'PERMISSION'  AND dsb.subject_id IN (:permissionIds))
--       OR (dsb.subject_type = 'GLOBAL_ROLE' AND dsb.subject_id IN (:globalRoleIds)) )
-- ORDER BY CASE dsp.effect WHEN 'DENY' THEN 0 ELSE 1 END,
--          CASE dsb.subject_type WHEN 'MEMBER' THEN 3 WHEN 'ROLE' THEN 2 ELSE 1 END DESC,
--          dsp.priority DESC;

-- ---- 11.4 组织树下钻（ORG_TREE 用的所有子组织 id）----
-- SELECT id FROM sys.org
-- WHERE tenant_id = :tenantId
--   AND deleted_at IS NULL
--   AND path LIKE (SELECT path FROM sys.org WHERE id = :orgId) || '%';
