package com.xiaolin.shared.infra.dao

import org.springframework.jdbc.core.namedparam.NamedParameterJdbcTemplate
import org.springframework.jdbc.support.GeneratedKeyHolder
import kotlin.reflect.KClass

/**
 * 数据库生成主键（BIGSERIAL / GENERATED ... AS IDENTITY）的 DAO 基类。
 *
 * 与 [AbstractJdbcDao] 的实质差异：id 不参与 INSERT，由数据库的
 * `DEFAULT nextval(...)` 填充，再通过 `RETURNING` 取回。
 *
 * 建表要求（Flyway）：
 * ```sql
 * CREATE TABLE orders (
 *     id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,  -- PG 10+ 推荐
 *     ...
 * );
 * ```
 * 注意区分两种：
 *  - GENERATED BY DEFAULT AS IDENTITY —— 允许显式插入 id（插 NULL 报错）
 *  - GENERATED ALWAYS AS IDENTITY     —— 完全禁止显式插入，必须靠本基类去掉 id 列
 * `BIGSERIAL` 是 PG 10 之前的旧写法，等价于 BY DEFAULT，新项目建议用 IDENTITY。
 */
abstract class AbstractSerialIdJdbcDao<T : Any>(
    jdbc: NamedParameterJdbcTemplate,
    entityClass: KClass<T>,
) : AbstractJdbcDao<T>(jdbc, entityClass) {

    /** id 由数据库生成，禁止出现在 INSERT 列里 */
    final override val idInInsert: Boolean get() = false

    /**
     * 插入并回填主键，返回带 id 的新实例。
     *
     * ```kotlin
     * val saved = dao.insertAndGet(order) { o, id -> o.copy(id = id) }
     * ```
     */
    open fun insertAndGet(entity: T, withId: (T, Long) -> T): T =
        withId(entity, insertReturningId(entity))

    /**
     * id 为 null 时提前失败。
     *
     * 否则 SQL 会变成 `WHERE id = NULL`，永远匹配不到行 ——
     * 没有 @Version 时静默影响 0 行，有 @Version 时报乐观锁冲突，错误信息都指向错误方向。
     */
    override fun update(entity: T): Int {
        val id = idOf(entity)
        require(id != null) {
            "Cannot update ${entityClass.simpleName} with null id. " +
                "Entity must be inserted first (id is generated by the database)."
        }
        return super.update(entity)
    }

    /**
     * 批量插入并取回自增主键。
     *
     * ⚠️ PostgreSQL 上的已知风险：
     *  1. **不要与 JDBC URL 参数 `reWriteBatchedInserts=true` 同时使用** ——
     *     驱动会把多条 INSERT 重写成 `VALUES (...), (...)` 单条语句，
     *     此时 generated keys 可能丢失或顺序错乱。
     *  2. 需要 id 且数据量不大 → 用 [insertAndGet] 单条插入（最可靠）
     *  3. 数据量大且不需要 id → 用 [insertBatch]（最快）
     *  4. 数据量大且必须要 id → 用 [nextIds] 预分配 id 后再 [insertBatch]
     *
     * @return 返回顺序与编译顺序一致；若某批未取回，长度可能小于入参
     */
    open fun insertBatchReturningIds(entities: List<T>, batchSize: Int = 500): List<Long> {
        if (entities.isEmpty()) return emptyList()
        val keyHolder = GeneratedKeyHolder()
        val args = entities.map(::toParams).toTypedArray()
        var from = 0
        while (from < args.size) {
            val to = minOf(from + batchSize, args.size)
            // 不要在此 SQL 上追加 RETURNING —— Spring 会用 RETURN_GENERATED_KEYS，
            // pgjdbc 自行追加，重复写会冲突
            jdbc.batchUpdate(insertSql, args.copyOfRange(from, to), keyHolder)
            from = to
        }
        return keyHolder.keyList.mapNotNull { entry ->
            (entry[idColumn] ?: entry.values.firstOrNull()) as? Long
        }
    }

    /**
     * 从序列批量预分配 id。
     *
     * 用于「大批量插入且必须知道每条的 id」的场景（如插入后要写子表外键）。
     * 步骤：`nextIds(n)` → 在应用层给实体赋 id → `insertBatch`（需临时允许 id 写入）。
     *
     * ⚠️ 预分配的 id 在并发写入下会与自增序列交错，id 不连续属正常现象，
     *     不要依赖 id 的单调连续性做任何业务判断。
     */
    open fun nextIds(count: Int): List<Long> {
        require(count > 0) { "count must be positive" }
        val seq = jdbc.queryForObject(
            "SELECT pg_get_serial_sequence(:t, :c)",
            paramsOf("t" to tableName, "c" to idColumn),
            String::class.java,
        ) ?: error("Cannot resolve sequence for $tableName.$idColumn")
        // seq 来自系统表且已被 quote，count 是 Int，两者均可安全拼接
        return jdbc.queryForList(
            "SELECT nextval('$seq') FROM generate_series(1, $count)",
            mapOf<String, Any?>(),
            Long::class.java,
        ).filterNotNull()
    }
}
